### ISSUE TITLE
Breaking changes from 3.2.2 to 3.2.3

### ISSUE THREAD

**Issue by zsid** [mui-org/material-ui-pickers#1273]
![Breaking change](https://media.giphy.com/media/3o7aD2w9xKVbQWoEQE/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.3      |
| material-ui          |    ^4.3.2     |
| React                |   ^16.8.6     |
| Browser              |   Chrome      |
| Peer library         |      "@date-io/date-fns": "^1.3.9", "date-fns": "^2.0.0-beta.5", |

## Steps to reproduce

1. This is not an obvious one - when a name of a third party component changes that causes our tests to break because `testcafe` needs `string` for their react selector. On a similar note I have seen failing tests when people are using snapshots for their jest tests -> these will also fail whenever the name change. i.e. the name changed from `WrappedPurePicker` to `PickerWithState`

2. I am using React + Typescript and when I updated from 3.2.2 to 3.2.3 my typescript compiler started complaining that `label` is not defined and started kicking about name  when I deleted label etc.

## Expected behavior
* When I downgrade to 3.2.2 everything works as expected and I dont need to change the props I am passing to the DatePicker component

## Actual behavior
Typescript error

## Live example
Code: We are using Formik for the forms so our component looks like this:
```
              <DateTimePicker
                data-tc="hello"
                key="hello"
                label="Hello"
                name="hello"
                showTodayButton
                allowKeyboardControl
                disablePast
                ampm={false}
                format="dd/MM/yyyy HH:mm"
                value={values.hello}
                onChange={value => setFieldValue('hello', value)}
                onClose={() => setFieldTouched('hello', true)}
              />
```
And when I have updated to version `3.2.3` it started throwing typescript errors:
```
  Property 'label' does not exist on type 'IntrinsicAttributes & DateValidationProps & BasePickerProps & { variant?: "inline" | "static" | "dialog" | undefined; } & Pick<ModalWrapperProps<{}>, "okLabel" | "cancelLabel" | ... 4 more ... | "DialogProps"> & Pick<...> & Pick<...> & DateTimePickerViewsProps & { ...; }'
```

**Comment by caitecoll** [comment]
I'm experiencing the same thing with the `autoOk` and `label` properties on the KeyboardDatePicker component. It works fine in 3.2.2 but throws type error with the upgrade to 3.2.3

**Comment by dmtrKovalenko** [comment]
Please provide a way to reproduce it. Everything works fine for me with latest mateiral-ui and material-ui-pickers

**Comment by sdirix** [comment]
See this [codesandbox](https://codesandbox.io/s/react-typescript-qskvd) to reproduce the issue. Note that it takes some time in codesandbox for the error to show up. `label` is correctly applied to the text input, however it is not accepted by the typings.

**Comment by Flash619** [comment]
I'm experiencing the same issue on 3.2.4. Dropping back to 3.2.2 fixed it.

**Comment by Achilles4400** [comment]
I'm experimenting the same issue in 3.2.5. This issue should be reopened
