### ISSUE TITLE
TypeScript overrides are not working with v4.0.0-alpha.8

### ISSUE THREAD

**Issue by bopfer** [mui-org/material-ui-pickers#1858]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     v4.0.0-alpha.8    |
| material-ui          |     4.10.0    |
| TypeScript           |    3.9.3     |
| React                |     16.13.1    |
| Browser              |    All     |
| Peer library         |    date-fns     |

## Steps to reproduce

Following the [TypeScript example](https://next.material-ui-pickers.dev/guides/css-overrides#typescript) for overriding CSS causes a type error in `@material-ui/core`.

I have the following in my TypeScript declaration file:

```typescript
import { MuiPickersComponentsToClassName } from '@material-ui/pickers/typings/overrides';

declare module '@material-ui/core/styles/overrides' {
  export interface ComponentNameToClassKey extends MuiPickersComponentsToClassName {}
}
```

> Side note: The example also references the `src` path, which is also doesn't work.   Removing `src` seems to make that import work.

## Expected behavior

`tsc` should pass.

## Actual behavior

When I run `tsc` on my project, I get the following error:

```
$ tsc -p tsconfig.json
../../../node_modules/@material-ui/core/styles/overrides.d.ts:100:64 - error TS2344: Type 'ComponentNameToClassKey[Name]' does not satisfy the constraint 'string'.
  Type '"fixed" | "required" | "default" | "square" | "active" | "disabled" | "track" | "error" | "progress" | "message" | "middle" | "media" | "hidden" | "body" | "button" | "caption" | ... 486 more ... | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.

100   [Name in keyof ComponentNameToClassKey]?: Partial<StyleRules<ComponentNameToClassKey[Name]>>;
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If I remove the picker overrides, `tsc` passes.

**Comment by oliviertassinari** [comment]
@bopfer Do you have a reproduction for the TypeScript fail? It seems to work fine: https://codesandbox.io/s/festive-golick-ej7q7?file=/src/theme.ts?

However, thanks for reporting thee other issues.

1. `MuiPickersComponentsToClassName` is likely not the correct name for the object. Following the convention in the core, I think that `PickersComponentsToClassKey` will be less confusing. We might handle the props at the same time:

```diff
diff --git a/lib/src/typings/overrides.ts b/lib/src/typings/overrides.ts
index df2d2058..aefae067 100644
--- a/lib/src/typings/overrides.ts
+++ b/lib/src/typings/overrides.ts
@@ -33,7 +33,7 @@ type Classes<T> = T extends string
   ? D
   : never;

-export interface MuiPickersComponentsToClassName {
+export interface PickersComponentsToClassKey {
   MuiPickersDay?: Classes<typeof DayStyles>;
   MuiPickerDTHeader?: Classes<typeof DTHeaderStyles>;
   MuiPickerDTTabs?: Classes<typeof DTTabsStyles>;
diff --git a/lib/src/typings/props.ts b/lib/src/typings/props.ts
index 993497e2..7b6cfadf 100644
--- a/lib/src/typings/props.ts
+++ b/lib/src/typings/props.ts
@@ -27,7 +27,7 @@ import {
   StaticDateRangePickerProps,
 } from '..';

-export interface MuiPickersComponentsPropsList {
+export interface PickersComponentsPropsList {
   MuiPickersDay: DayProps;
   MuiPickersCalendarView: CalendarViewProps;
   MuiPickersDatePicker: DatePickerProps;
```

2. The import path is wrong in the documentation:

```diff
diff --git a/docs/pages/guides/css-overrides.mdx b/docs/pages/guides/css-overrides.mdx
index e7ab9fd9..b8fdb20a 100644
--- a/docs/pages/guides/css-overrides.mdx
+++ b/docs/pages/guides/css-overrides.mdx
@@ -46,7 +46,7 @@ Add the following to a TypeScript declaration file in your project, such as `ove
 <!-- should be in sync with lib/src/__tests__/typings.d.ts -->

 ```typescript
-import { MuiPickersComponentsToClassName } from '@material-ui/pickers/src/typings/overrides';
+import { PickersComponentsToClassKey } from '@material-ui/pickers/typings/overrides';

 declare module '@material-ui/core/styles/overrides' {
   export interface ComponentNameToClassKey extends MuiPickersComponentsToClassName {}
```
3. Depending on how https://github.com/mui-org/material-ui/pull/21279 go, we might want to change the approach here too.

**Comment by bopfer** [comment]
Sorry, should have added that the overrides do work in the sense that I don't get any errors in my `theme.ts` file itself.  The error only shows up when I run `tsc`.  I will create a small repo to reproduce and to verify that it is an isolated issue and not something with my project setup.

**Comment by bopfer** [comment]
Here is a reproduction: https://github.com/bopfer/mui-picker-overrides.  The README in there has notes about the setup and how to reproduce the error.

**Comment by oliviertassinari** [comment]
@bopfer Any idea what could be wrong?

**Comment by dmtrKovalenko** [comment]
I am not sure it doesn't work for you...

Are you sure that `types` folder included? I am always explicitly adding it with `includes`

**Comment by bopfer** [comment]
`src/types` is included by default.  If I open `src/types/overrides-mui.d.ts` and comment out all the lines, then `tsc` will pass.

I am not sure exactly what's wrong.  It looks like one of the picker overrides has `undefined` as a possibly key and `@material-ui/core/styles/overrides.d.ts` does not allow that.

**Comment by oliviertassinari** [comment]
@bopfer I had a closer look at the problem. It seems to be coming from a divergence with the core's approach: https://github.com/mui-org/material-ui/blob/51b6ea9626a1be8304e495b39cd9ed6ca1ce5c0d/packages/material-ui/src/styles/overrides.d.ts#L110.

Could you confirm that this diff solves the issue?

```diff
diff --git a/lib/src/typings/overrides.ts b/lib/src/typings/overrides.ts
index df2d2058..78e53d5c 100644
--- a/lib/src/typings/overrides.ts
+++ b/lib/src/typings/overrides.ts
@@ -34,35 +34,35 @@ type Classes<T> = T extends string
   : never;

 export interface MuiPickersComponentsToClassName {
-  MuiPickersDay?: Classes<typeof DayStyles>;
-  MuiPickerDTHeader?: Classes<typeof DTHeaderStyles>;
-  MuiPickerDTTabs?: Classes<typeof DTTabsStyles>;
-  MuiPickersCalendar?: Classes<typeof CalendarStyles>;
-  MuiPickersCalendarView?: Classes<typeof CalendarViewStyles>;
-  MuiPickersCalendarHeader?: Classes<typeof CalendarHeaderStyles>;
-  MuiPickersSlideTransition?: Classes<typeof SlideTransitionStyles>;
-  MuiPickersYearSelection?: Classes<typeof MuiPickersYearSelectionStyles>;
-  MuiPickersYear?: Classes<typeof MuiPickersYearStyles>;
-  MuiPickersMonthSelection?: Classes<typeof MuiPickersMonthSelectionStyles>;
-  MuiPickersMonth?: Classes<typeof MuiPickersMonthStyles>;
-  MuiPickersTimePickerToolbar?: Classes<typeof TimePickerToolbarStyles>;
-  MuiPickersClock?: Classes<typeof ClockStyles>;
-  MuiPickersClockNumber?: Classes<typeof ClockNumberStyles>;
-  MuiPickersClockPointer?: Classes<typeof ClockPointerStyles>;
-  MuiPickersToolbar?: Classes<typeof PickerToolbarStyles>;
-  MuiPickersToolbarButton?: Classes<typeof ToolbarButtonStyles>;
-  MuiPickersToolbarText?: Classes<typeof MuiPickersToolbarTextStyles>;
-  MuiPickersDatePickerRoot?: Classes<typeof DatePickerRootStyles>;
-  MuiPickerDTToolbar?: Classes<typeof MuiPickerDTToolbarStyles>;
-  MuiBasePickerStyles?: Classes<typeof MuiBasePickerStyles>;
+  MuiPickersDay: Classes<typeof DayStyles>;
+  MuiPickerDTHeader: Classes<typeof DTHeaderStyles>;
+  MuiPickerDTTabs: Classes<typeof DTTabsStyles>;
+  MuiPickersCalendar: Classes<typeof CalendarStyles>;
+  MuiPickersCalendarView: Classes<typeof CalendarViewStyles>;
+  MuiPickersCalendarHeader: Classes<typeof CalendarHeaderStyles>;
+  MuiPickersSlideTransition: Classes<typeof SlideTransitionStyles>;
+  MuiPickersYearSelection: Classes<typeof MuiPickersYearSelectionStyles>;
+  MuiPickersYear: Classes<typeof MuiPickersYearStyles>;
+  MuiPickersMonthSelection: Classes<typeof MuiPickersMonthSelectionStyles>;
+  MuiPickersMonth: Classes<typeof MuiPickersMonthStyles>;
+  MuiPickersTimePickerToolbar: Classes<typeof TimePickerToolbarStyles>;
+  MuiPickersClock: Classes<typeof ClockStyles>;
+  MuiPickersClockNumber: Classes<typeof ClockNumberStyles>;
+  MuiPickersClockPointer: Classes<typeof ClockPointerStyles>;
+  MuiPickersToolbar: Classes<typeof PickerToolbarStyles>;
+  MuiPickersToolbarButton: Classes<typeof ToolbarButtonStyles>;
+  MuiPickersToolbarText: Classes<typeof MuiPickersToolbarTextStyles>;
+  MuiPickersDatePickerRoot: Classes<typeof DatePickerRootStyles>;
+  MuiPickerDTToolbar: Classes<typeof MuiPickerDTToolbarStyles>;
+  MuiBasePickerStyles: Classes<typeof MuiBasePickerStyles>;
   // consider using inline import type notation
-  MuiPickersDesktopDateRangeCalendar?: Classes<
+  MuiPickersDesktopDateRangeCalendar: Classes<
     typeof import('../DateRangePicker/DateRangePickerViewDesktop').useStyles
   >;
-  MuiPickersArrowSwitcher?: Classes<typeof import('../_shared/ArrowSwitcher').useStyles>;
-  MuiPickersDateRangePickerInput?: Classes<
+  MuiPickersArrowSwitcher: Classes<typeof import('../_shared/ArrowSwitcher').useStyles>;
+  MuiPickersDateRangePickerInput: Classes<
     typeof import('../DateRangePicker/DateRangePickerInput').useStyles
   >;
-  MuiPickersModalDialog?: Classes<typeof import('../_shared/PickerModalDialog').useStyles>;
-  MuiPickersCalendarSkeleton?: Classes<typeof import('../CalendarSkeleton').useStyles>;
+  MuiPickersModalDialog: Classes<typeof import('../_shared/PickerModalDialog').useStyles>;
+  MuiPickersCalendarSkeleton: Classes<typeof import('../CalendarSkeleton').useStyles>;
 }
```

**Comment by bopfer** [comment]
@oliviertassinari Confirmed.  The type check passes with that diff.

**Comment by oliviertassinari** [comment]
Great, if you want to do the changes, feel free to. Otherwise, I think that we should wait for the resolution of https://github.com/mui-org/material-ui/pull/21279 to apply the same approach to the pickers in order to close the issue.
