### ISSUE TITLE
TypeError: utils.getYearText is not a function when updating @date-io/moment to v2.0.1

### ISSUE THREAD

**Issue by efstathiosntonas** [mui-org/material-ui-pickers#1442]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.8     |
| material-ui          |   4.8.2      |
| TypeScript           |         |
| React                |     16.12    |
| Browser              |   chrome      |
| Peer library         |    @date-io/moment     |  |

## Steps to reproduce

Updated @date-io/moment to version 2.0.1

## Expected behavior

get back getYearText function
## Actual behavior
 utils.getYearText is not a function

Reverted back to   "@date-io/moment": "^1.3.13" and everything works fine
## Live example

![Screenshot at Jan 08 14-57-58](https://user-images.githubusercontent.com/717975/71980068-e5477400-3227-11ea-8ac2-54cc6bda17ca.png)

**Comment by dmtrKovalenko** [comment]
Duplicate of #1440

**Comment by glocore** [comment]
This happened to me when I installed the latest version of `@date-io/dayjs` with `dayjs`. I was able to fix it by instead installing version 1.x of date-io, as mentioned in the docs:

```bash
$ npm install @date-io/dayjs@1.x
```

This will install the latest version under the 1.x series.
